server:
  port: 8888

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atguigudb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  task:
    execution:
      simple:
        pool:
          core-size: 9
      pool:
        core-size: 8
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


plugin:
  mybatis:
    print-sql: true
    xml-reload: true
    sql-method:
      - type: MYSQL
  script:
    config:
      #      - source: E:\workspace\spring-starter-support-parent\spring-demo-server\src\main\resources
      - type: MYSQL


  core:
    open-version: true
  cors:
    enable: true
  oauth:
    server:
      open-check-ak-sk: false
  log:
    mysql:
      - host: 127.0.0.1
        user: root
        password: root
        listener: mysql
  view:
    open-view: true
    config:
      oss:
        path: Z://other
        plugins:
#  remote:
#    application:
#      name: server
#    protocols:
#      - name: dubbo
#        port: 20880
#    registry:
#      protocol: zookeeper
management:
  endpoints:
    web:
      exposure:
        include: '*'

#      address: 127.0.0.1:2181